kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: app1

spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.pathPrefix }}
            pathType: Prefix
            backend:
              service:
                name: app1
                port:
                  number: 8913