apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}

spec:
  type: ClusterIP
  ports:
    - port: 8913
      targetPort: 80
      protocol: TCP
  selector:
      app: {{ .Release.Name }}