

# Example configuration of using an external Traefik Ingress provider.
# https://docs.gitlab.com/charts/charts/traefik/

global:
  edition: ce
  hosts:
    domain: cluster
    externalIP: 127.0.0.1
    https: false
  certmanager:
    install: false

  ingress:
    # Disable th cert-manager integration.
    configureCertmanager: false

    # Default, present here to be explicit.
    enabled: true
    # Toggle the TCP configuration and annotations to Traefik.
    provider: traefik
    # Alter the `kubernetes.io/ingress.class` annotation or
    # `spec.ingressClassName` value chart-wide.
    class: traefik
    annotations:
      # Tell Traefik that we've configured TLS
      # NOTE: disable this if `global.ingress.tls.enabled=false`.
      traefik.ingress.kubernetes.io/router.tls: "true"
      # Ensure the HTTP Routes only listen on 443, rather than all entrypoints.
      # NOTE: set the value to `web` if `global.ingress.tls.enabled=false`.
      traefik.ingress.kubernetes.io/router.entrypoints: websecure

nginx-ingress:
  # Disable the deployment of the in-chart NGINX Ingress provider.
  enabled: false

traefik:
  install: true
  # Ensure the IngressClass name and `global.ingress.class` value match.
  # This can be removed if `global.ingress.class` is set to `$releaseName-traefik`.
  fullnameOverride: traefik
  ingressClass:
    # Create an IngressClass object for Traefik.
    enabled: true
    # Helps an avoid error when making local templates.
    fallbackApiVersion: v1

gitlab-runner:
  # Disable the deployment of the in-chart GitLab Runner.
  install: false
